<script setup>
import { ref, computed, watch } from 'vue'
import { connectionState, startSerialDfu, dfuActive } from '../lib/store.js'
import { isWebSerialAvailable } from '../lib/dfu/serial.js'
import { parseDfuZip, getDfuPackageInfo } from '../lib/dfu/zip.js'

const expanded = ref(false)

// Auto-expand when DFU is active (BLE disconnected, serial transfer in progress)
watch(dfuActive, (active) => { if (active) expanded.value = true })
const webSerialOk = computed(() => isWebSerialAvailable())

// State machine: idle → parsed → confirm → rebooting → waiting-port → transferring → complete → error
const state = ref('idle')
const progress = ref(0)
const progressMsg = ref('')
const errorMsg = ref('')

// Parsed DFU package
const packageInfo = ref(null)
let datFile = null
let binFile = null

// Port selection resolver (called from onWaitingPort)
let portResolve = null

function onFileSelect(e) {
  const file = e.target.files[0]
  if (!file) return

  if (!file.name.endsWith('.zip')) {
    errorMsg.value = 'Please select a .zip DFU package'
    state.value = 'error'
    return
  }

  const reader = new FileReader()
  reader.onload = () => {
    try {
      const result = parseDfuZip(reader.result)
      datFile = result.datFile
      binFile = result.binFile
      packageInfo.value = getDfuPackageInfo(result.manifest, binFile)
      state.value = 'parsed'
      errorMsg.value = ''
    } catch (err) {
      errorMsg.value = err.message
      state.value = 'error'
    }
  }
  reader.readAsArrayBuffer(file)
}

function startUpdate() {
  state.value = 'confirm'
}

async function confirmUpdate() {
  state.value = 'rebooting'
  progress.value = 0
  progressMsg.value = ''

  try {
    await startSerialDfu(
      datFile,
      binFile,
      (pct, msg) => {
        progress.value = pct
        progressMsg.value = msg
        if (pct > 0 && state.value !== 'transferring') {
          state.value = 'transferring'
        }
      },
      () => {
        // onWaitingPort: switch to waiting-port state and wait for user click
        state.value = 'waiting-port'
        return new Promise(resolve => { portResolve = resolve })
      },
    )
    state.value = 'complete'
  } catch (err) {
    errorMsg.value = err.message
    state.value = 'error'
  }
}

function selectPort() {
  if (portResolve) {
    portResolve()
    portResolve = null
  }
}

function reset() {
  state.value = 'idle'
  progress.value = 0
  progressMsg.value = ''
  errorMsg.value = ''
  packageInfo.value = null
  datFile = null
  binFile = null
  dfuActive.value = false
}

function cancel() {
  state.value = packageInfo.value ? 'parsed' : 'idle'
}
</script>

<template>
  <section class="card dfu-card">
    <h2 @click="expanded = !expanded" class="dfu-header">
      Firmware Update
      <span class="expand-icon">{{ expanded ? '▾' : '▸' }}</span>
    </h2>

    <div v-if="expanded" class="dfu-body">
      <!-- Web Serial check -->
      <div v-if="!webSerialOk" class="dfu-warning">
        Web Serial is not available. Use Chrome or Edge on desktop.
      </div>

      <template v-else>
        <!-- idle: file picker -->
        <div v-if="state === 'idle'" class="dfu-step">
          <p class="help-text">Select a DFU package (.zip) generated by adafruit-nrfutil.</p>
          <input type="file" accept=".zip" @change="onFileSelect" class="file-input" />
        </div>

        <!-- parsed: show package info + start button -->
        <div v-else-if="state === 'parsed'" class="dfu-step">
          <div class="pkg-info">
            <span>Firmware size: <strong>{{ packageInfo.firmwareSizeKB }} KB</strong></span>
          </div>
          <p class="help-text dfu-usb-note">
            USB cable must be connected to the device before starting.
          </p>
          <div class="dfu-actions">
            <button class="btn btn-accent" @click="startUpdate">Start Firmware Update</button>
            <button class="btn" @click="reset">Cancel</button>
          </div>
        </div>

        <!-- confirm: final confirmation -->
        <div v-else-if="state === 'confirm'" class="dfu-step">
          <p class="dfu-confirm-msg">
            This will reboot the device into USB DFU mode. BLE will disconnect.
            Make sure the USB cable is connected.
          </p>
          <p class="dfu-confirm-warning">
            Do not disconnect USB during the transfer. If the update fails
            after starting, you will need to reflash via Arduino IDE or UF2.
          </p>
          <div class="dfu-actions">
            <button class="btn btn-warning" @click="confirmUpdate">Confirm Update</button>
            <button class="btn" @click="cancel">Cancel</button>
          </div>
        </div>

        <!-- rebooting: waiting for device to reboot -->
        <div v-else-if="state === 'rebooting'" class="dfu-step">
          <div class="dfu-spinner"></div>
          <p>{{ progressMsg || 'Rebooting into DFU mode...' }}</p>
        </div>

        <!-- waiting-port: user must select serial port -->
        <div v-else-if="state === 'waiting-port'" class="dfu-step">
          <p>Device is in DFU mode. Select the USB serial port to begin transfer.</p>
          <p class="help-text">Choose the same port the device was using (e.g. "usbmodem2101").</p>
          <button class="btn btn-accent" @click="selectPort">Select Serial Port</button>
        </div>

        <!-- transferring: progress bar -->
        <div v-else-if="state === 'transferring'" class="dfu-step">
          <div class="progress-bar-container">
            <div class="progress-bar" :style="{ width: progress + '%' }"></div>
          </div>
          <div class="progress-info">
            <span class="progress-pct">{{ progress }}%</span>
            <span class="progress-msg">{{ progressMsg }}</span>
          </div>
        </div>

        <!-- complete: success -->
        <div v-else-if="state === 'complete'" class="dfu-step dfu-success">
          <p>Firmware update complete! The device is rebooting with the new firmware.</p>
          <p class="help-text">Reconnect via BLE to verify the new version.</p>
          <button class="btn" @click="reset">Done</button>
        </div>

        <!-- error: show error + retry -->
        <div v-else-if="state === 'error'" class="dfu-step dfu-error">
          <p class="error-text">{{ errorMsg }}</p>
          <p class="help-text">If the device is stuck in DFU mode, power cycle it (unplug USB and battery).</p>
          <button class="btn" @click="reset">Try Again</button>
        </div>
      </template>
    </div>
  </section>
</template>

<style scoped>
.dfu-card {
  border-color: var(--border);
}

.dfu-header {
  cursor: pointer;
  display: flex;
  justify-content: space-between;
  align-items: center;
  user-select: none;
  margin-bottom: 0;
}

.dfu-header:hover {
  opacity: 0.8;
}

.expand-icon {
  font-size: 0.8rem;
  color: var(--text-dim);
}

.dfu-body {
  margin-top: 0.75rem;
}

.dfu-step {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.dfu-warning {
  padding: 0.75rem;
  background: rgba(239, 83, 80, 0.1);
  border: 1px solid var(--danger);
  border-radius: 6px;
  color: var(--danger);
  font-size: 0.9rem;
}

.file-input {
  font-size: 0.9rem;
  color: var(--text);
}

.file-input::file-selector-button {
  padding: 0.4rem 1rem;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--surface-2);
  color: var(--text);
  cursor: pointer;
  margin-right: 0.75rem;
}

.file-input::file-selector-button:hover {
  background: var(--surface-1);
  border-color: var(--text-dim);
}

.pkg-info {
  font-size: 0.9rem;
  font-family: 'SF Mono', 'Fira Code', monospace;
}

.pkg-info strong {
  color: var(--accent);
}

.dfu-usb-note {
  padding: 0.5rem 0.75rem;
  background: rgba(255, 167, 38, 0.1);
  border: 1px solid var(--warning);
  border-radius: 6px;
  color: var(--warning);
}

.dfu-actions {
  display: flex;
  gap: 0.75rem;
}

.btn-accent {
  background: var(--accent);
  color: #000;
  border-color: var(--accent);
  font-weight: 600;
}

.btn-accent:hover:not(:disabled) {
  background: var(--accent-hover);
  border-color: var(--accent-hover);
}

.dfu-confirm-msg {
  font-size: 0.9rem;
  line-height: 1.6;
}

.dfu-confirm-warning {
  padding: 0.5rem 0.75rem;
  background: rgba(239, 83, 80, 0.1);
  border: 1px solid var(--danger);
  border-radius: 6px;
  color: var(--danger);
  font-size: 0.85rem;
  line-height: 1.5;
}

.dfu-spinner {
  width: 24px;
  height: 24px;
  border: 3px solid var(--border);
  border-top-color: var(--accent);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.progress-bar-container {
  width: 100%;
  height: 8px;
  background: var(--surface-2);
  border-radius: 4px;
  overflow: hidden;
}

.progress-bar {
  height: 100%;
  background: var(--accent);
  border-radius: 4px;
  transition: width 0.3s ease;
}

.progress-info {
  display: flex;
  justify-content: space-between;
  font-size: 0.85rem;
}

.progress-pct {
  font-weight: 600;
  font-family: 'SF Mono', 'Fira Code', monospace;
  color: var(--accent);
}

.progress-msg {
  color: var(--text-dim);
}

.dfu-success p:first-child {
  color: #66bb6a;
}

.dfu-error .error-text {
  color: var(--danger);
  font-family: 'SF Mono', 'Fira Code', monospace;
  font-size: 0.85rem;
}
</style>
