/**
 * DFU ZIP package parser.
 * Uses fflate for ZIP decompression.
 *
 * Expected ZIP structure (generated by adafruit-nrfutil dfu genpkg):
 *   manifest.json — describes the package contents
 *   *.dat        — init packet (DFU settings: device type, revision, CRC)
 *   *.bin        — firmware binary image
 */
import { unzipSync } from 'fflate'

/**
 * Parse a DFU ZIP package.
 * @param {ArrayBuffer} arrayBuffer - Raw ZIP file bytes
 * @returns {{ manifest: object, datFile: Uint8Array, binFile: Uint8Array }}
 */
export function parseDfuZip(arrayBuffer) {
  const files = unzipSync(new Uint8Array(arrayBuffer))

  // Find manifest.json
  const manifestKey = Object.keys(files).find(k => k.endsWith('manifest.json'))
  if (!manifestKey) {
    throw new Error('Invalid DFU package: missing manifest.json')
  }

  const manifest = JSON.parse(new TextDecoder().decode(files[manifestKey]))

  // Find the application entry in manifest
  const app = manifest.manifest?.application
  if (!app) {
    throw new Error('Invalid DFU package: no application entry in manifest')
  }

  // Extract .dat and .bin filenames from manifest
  const datName = app.dat_file
  const binName = app.bin_file

  if (!datName || !binName) {
    throw new Error('Invalid DFU package: missing dat_file or bin_file in manifest')
  }

  const datFile = files[datName]
  const binFile = files[binName]

  if (!datFile) {
    throw new Error(`Invalid DFU package: ${datName} not found in ZIP`)
  }
  if (!binFile) {
    throw new Error(`Invalid DFU package: ${binName} not found in ZIP`)
  }

  return { manifest, datFile, binFile }
}

/**
 * Get display info about a DFU package.
 * @param {object} manifest - Parsed manifest.json
 * @param {Uint8Array} binFile - Firmware binary
 * @returns {{ firmwareSize: number, firmwareSizeKB: string }}
 */
export function getDfuPackageInfo(manifest, binFile) {
  return {
    firmwareSize: binFile.length,
    firmwareSizeKB: (binFile.length / 1024).toFixed(1),
  }
}
